//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA
    {
        public int id_cuenta { get; set; }
        public int id_usuario { get; set; }
        public string numero_cuenta { get; set; }
        public int saldo { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
